### PR TITLE
Fixed build to publish version 1.0

### PR DESCRIPTION
**Pull request by sbi-scireum**

### CODE REVIEW

**Comment by scireumskip** [comment]
Can one of the admins verify this patch?

**Comment by andyHa** [comment]
Yes

**Comment by andyHa** [comment]
ok to test

**Comment by scireumskip** [comment]
Can one of the admins verify this patch?

**Comment by sbi-scireum** [comment]
build

**Comment by sbi-scireum** [comment]
build

**Comment by sbi-scireum** [comment]
build

**Pull request merged**
